manifest:
  version: 1.0

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.4.2
      import:
        name-allowlist:
          - cmsis_6
          - hal_nxp
          - hal_rpi_pico
          - hal_infineon # Needed for rpi_pico
          - hal_espressif
          - hal_nordic
        path-prefix: deps
