CONFIG_GPIO=y
CONFIG_LOG=y

# Needed for RPI Pico W
CONFIG_CYW43439=y
CONFIG_NETWORKING=y
CONFIG_WIFI=y
CONFIG_WIFI_AIROC=y
CONFIG_GPIO_CYW43=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

# USB Console configuration
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_UART_LINE_CTRL=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Here set to redirect stdout/log to USB CDC
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y