# Logging settings
CONFIG_LOG=y

# GPIO Settings
CONFIG_GPIO=y
CONFIG_PWM=y

# USB Console configuration
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_CDC_ACM=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y

# Blink Config
CONFIG_LED_SUBSYSTEM=y
CONFIG_BLINK_SLEEP_500MS=y
CONFIG_LED_ADVANCED=y
CONFIG_LED_BRIGHTNESS=100
CONFIG_LED_FADE_DURATION=500
CONFIG_LED_DEBUGGING=y
# CONFIG_LED_CUSTOM_BLINK=n